<a href="https://colab.research.google.com/github/Renzou1/treinamento-h2ia/blob/main/01_Relat%C3%B3rio_Buscas_sem_informa%C3%A7%C3%A3o_para_blocos_deslizantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# O Problema
Sliding Puzzle - Bloco Deslizante

In [ ]:
# !wget -qq https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif
from IPython.display import Image
Image(url='https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif',width=200)

# Resolver o quebra-cabeças usando Buscas

In [2]:
# Setting up
# 0 = blank space
import numpy as np
from collections import deque

def goal_reached(state):
  return np.array_equal(state, np.arange(9))

def create_initial_state():
  arr = np.arange(9)
  np.random.shuffle(arr)
  return arr

# "move" does not refer to the direction the blank space goes, but rather the tile that was moved to the blank space.
def move_down(state):
  local = list(state)
  zero = local.index(0)
  if zero - 3 >= 0:
    local[zero], local[zero - 3] = local[zero - 3], local[zero]
    return local
  return None

def move_up(state):
  local = list(state)
  zero = local.index(0)
  if zero + 3 < 9:
    local[zero], local[zero + 3] = local[zero + 3], local[zero]
    return local
  return None

def move_left(state):
  local = list(state)
  zero = local.index(0)
  if zero // 3 == (zero + 1) // 3:
    local[zero], local[zero + 1] = local[zero + 1], local[zero]
    return local
  return None

def move_right(state):
  local = list(state)
  zero = local.index(0)
  if zero // 3 == (zero - 1) // 3:
    local[zero], local[zero - 1] = local[zero - 1], local[zero]
    return local
  return None

def print_solution(node):
  states = deque()
  actions = deque()
  while node.parent != None:
    states.append(node.state)
    if node.action == move_right:
      actions.append("move right:")
    elif node.action == move_left:
      actions.append("move left:")
    elif node.action == move_down:
      actions.append("move down:")
    elif node.action == move_up:
      actions.append("move up:")

    node = node.parent
    if(node.parent == None): #initial state
      states.append(node.state)
      actions.append("Initial State: ")

  while len(states) != 0:
    current = states.pop()
    print(actions.pop())
    print(current[:3])
    print(current[3:6])
    print(current[6:9])

In [3]:
class node:
  def __init__(self, parent=None, action=None, cost=0, state=None):
    self.parent = parent
    self.action = action
    if parent == None:
      self.state = create_initial_state()
      self.cost = 0
    else:
      self.state = action(parent.state)
      self.cost = parent.cost + 1

  def add_child(self, action):
    next_state = action(self.state)
    if next_state != None:
      return node(self, action, self.cost + 1, next_state)
    else:
      return None

  def set_initial_state(self, state):
    self.state = np.array(state)

## Busca em largura

In [19]:
def breadth_first_search(initial_state=None):
  root = node()
  if initial_state != None:
    root.set_initial_state(initial_state)

  actions = [move_up, move_right, move_left, move_down]
  if goal_reached(root.state):
    return 0
  queue = deque()
  queue.append(root)
  explored_states = set()
  while True:
    current = queue.popleft()
    explored_states.add(tuple(current.state))
    for action in actions:
      child = current.add_child(action)
      if child != None:
        if tuple(child.state) not in explored_states and child not in queue:
          if goal_reached(child.state):
            print_solution(child)
            return child.cost
          queue.append(child)

print("Total moves:", breadth_first_search())

Initial State: 
[1 7 6]
[4 5 3]
[0 2 8]
move down:
[1, 7, 6]
[0, 5, 3]
[4, 2, 8]
move down:
[0, 7, 6]
[1, 5, 3]
[4, 2, 8]
move left:
[7, 0, 6]
[1, 5, 3]
[4, 2, 8]
move left:
[7, 6, 0]
[1, 5, 3]
[4, 2, 8]
move up:
[7, 6, 3]
[1, 5, 0]
[4, 2, 8]
move right:
[7, 6, 3]
[1, 0, 5]
[4, 2, 8]
move up:
[7, 6, 3]
[1, 2, 5]
[4, 0, 8]
move left:
[7, 6, 3]
[1, 2, 5]
[4, 8, 0]
move down:
[7, 6, 3]
[1, 2, 0]
[4, 8, 5]
move right:
[7, 6, 3]
[1, 0, 2]
[4, 8, 5]
move right:
[7, 6, 3]
[0, 1, 2]
[4, 8, 5]
move down:
[0, 6, 3]
[7, 1, 2]
[4, 8, 5]
move left:
[6, 0, 3]
[7, 1, 2]
[4, 8, 5]
move left:
[6, 3, 0]
[7, 1, 2]
[4, 8, 5]
move up:
[6, 3, 2]
[7, 1, 0]
[4, 8, 5]
move up:
[6, 3, 2]
[7, 1, 5]
[4, 8, 0]
move right:
[6, 3, 2]
[7, 1, 5]
[4, 0, 8]
move right:
[6, 3, 2]
[7, 1, 5]
[0, 4, 8]
move down:
[6, 3, 2]
[0, 1, 5]
[7, 4, 8]
move down:
[0, 3, 2]
[6, 1, 5]
[7, 4, 8]
move left:
[3, 0, 2]
[6, 1, 5]
[7, 4, 8]
move up:
[3, 1, 2]
[6, 0, 5]
[7, 4, 8]
move up:
[3, 1, 2]
[6, 4, 5]
[7, 0, 8]
move right:
[3, 1, 2]
[6

## Busca em Profundidade

In [13]:
CUT = False
FAIL = True

def depth_first_search(max_depth, initial_state=None):
  root = node()
  if initial_state != None:
    root.set_initial_state(initial_state)

  actions = [move_up, move_right, move_left, move_down]
  return depth_first_recursive(root, max_depth, actions)

def depth_first_recursive(node, max_depth, actions):

  if goal_reached(node.state):
    print_solution(node)
    return node.cost
  elif max_depth == 0:
    return CUT
  else:
    for action in actions:
      child = node.add_child(action)
      if child != None: # impossible move
        result = depth_first_recursive(child, max_depth - 1, actions)
        if result == CUT:
          limit_reached = True
        elif result != FAIL:
          return result
    if limit_reached:
      return CUT
    else:
      return FAIL



print("Total moves:", depth_first_search(20, [1,0,2,3,4,5,6,7,8]))

Initial State: 
[1 0 2]
[3 4 5]
[6 7 8]
move up:
[1, 4, 2]
[3, 0, 5]
[6, 7, 8]
move up:
[1, 4, 2]
[3, 7, 5]
[6, 0, 8]
move right:
[1, 4, 2]
[3, 7, 5]
[0, 6, 8]
move left:
[1, 4, 2]
[3, 7, 5]
[6, 0, 8]
move right:
[1, 4, 2]
[3, 7, 5]
[0, 6, 8]
move left:
[1, 4, 2]
[3, 7, 5]
[6, 0, 8]
move right:
[1, 4, 2]
[3, 7, 5]
[0, 6, 8]
move left:
[1, 4, 2]
[3, 7, 5]
[6, 0, 8]
move right:
[1, 4, 2]
[3, 7, 5]
[0, 6, 8]
move left:
[1, 4, 2]
[3, 7, 5]
[6, 0, 8]
move right:
[1, 4, 2]
[3, 7, 5]
[0, 6, 8]
move left:
[1, 4, 2]
[3, 7, 5]
[6, 0, 8]
move right:
[1, 4, 2]
[3, 7, 5]
[0, 6, 8]
move left:
[1, 4, 2]
[3, 7, 5]
[6, 0, 8]
move right:
[1, 4, 2]
[3, 7, 5]
[0, 6, 8]
move left:
[1, 4, 2]
[3, 7, 5]
[6, 0, 8]
move down:
[1, 4, 2]
[3, 0, 5]
[6, 7, 8]
move down:
[1, 0, 2]
[3, 4, 5]
[6, 7, 8]
move right:
[0, 1, 2]
[3, 4, 5]
[6, 7, 8]
Total moves: 19


## Discorra sobre o desempenho dos métodos em questões de:


1.   Consumo de memória
2.   Processamento



In [ ]:
# Os dois métodos, como buscas sem informação, tem complexidade de tempo e espaço bem ruins. Como diz o terceiro capítulo do livro de Inteligência Artifical de Russel e Norvig,
# a "breadth first search" teria uma complexidade temporal de b^d, onde b é o fator de ramificação e d a profundidade.
# Já a "depth first search", tem complexidade temporal é de b^m, onde m é a profundidade máxima de qualquer nó (ou, do jeito que foi programado, a complexidade posta como limite).
# Falando sobre complexidade espacial, a depth first search tem vantagem pois pode limpar um caminho de nós depois de ter atingido seu limite,
# enquanto BFS teria que guardar todos os nós ao mesmo tempo até uma solução ser encontrada.

# Como, novamente, diz o livro, estes tipo de busca não são adequadas para problemas mais complexos, com complexidade exponencial por exemplo,
# visto que podem chegar a precisar de petabytes de memória para terminar.
# Como o problema dos blocos deslizantes é simples, eles podem ser utilizados com relativo sucesso,
# em especial o BFS já que consegue achar a solução ótima: ele sempre encontra a solução mais rasa, e em problemas como esse em que
# todas ações tem o mesmo custo, a solução mais rasa é a solução ótima.